services:
  collabora:
    image: ${COLLABORA_IMAGE:-collabora/code:24.04.5.1.1}
    container_name: seafile-collabora
    networks:
      - seafile-net
      - extern
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - DONT_GEN_SSL_CERT=true
      # - server_name=collabora:9980 # ${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}:${COLLABORA_PORT:-6232}
      - TZ=${TIME_ZONE:-Europe/Berlin}
      # - username=${COLLABORA_USERNAME:?Variable is not set or empty}
      # - password=${COLLABORA_PASSWORD:?Variable is not set or empty}
      - extra_params=--o:admin_console.enable=${COLLABORA_ENABLE_ADMIN_CONSOLE:-true}
        --o:ssl.enable=false
        --o:ssl.termination=true
        --o:user_interface.mode=classic
        --o:remote_font_config.url=${COLLABORA_REMOTE_FONT:-}
        --o:logging.file[@enable]=${COLLABORA_ENABLE_FILE_LOGGING:-false}
        --o:logging.file.property[0]=/opt/cool/logs/coolwsd.log
      - VIRTUAL_HOST=doc.${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty
      - VIRTUAL_PORT=${COLLABORA_PORT:?Variable is not set or empty}
      - LETSENCRYPT_HOST=doc.${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
